
def list_devices() -> list[str]: ...


class Device:
    def __init__(self) -> None: ...
    def open(self, dev_name: str, baud: int, interface_index: int) -> int: ...
    def close(self) -> int: ...
    def set_sync_mode(self, is_sync_mode: bool) -> int: ...
    def is_connected(self) -> bool: ...
    def clear_buffers(self) -> int: ...
    def send(self, data: list[int]) -> int: ...
    def read(self, size: int, timeout: float) -> tuple[int, list[int]]: ...
